### ISSUE TITLE
Activation issue

### ISSUE THREAD

**Issue by brunotoshio** [ikegami-yukino/pymlask#11]
Hi,

I think I found a bug related to the activation. 
```python
from mlask import MLAsk

ma = MLAsk()
ma.analyze('嫌です')    # => activation = ACTIVE, but it should be NEUTRAL
```
The problem is that you are counting the number of letters `A` after the regular expression substitutions without taking into account that the word `NEUTRAL` also has a letter `A`. Therefore, the emotion `iya`, which belongs to NEUTRAL, is being counted as an `A` (active) too.

**Comment by ikegami-yukino** [comment]
Thank you for reporting this issue.
I resolved it 😃
