### ISSUE TITLE
Troubles on Trying Sample Code

### ISSUE THREAD

**Issue by EgnaroJQ** [ikegami-yukino/pymlask#15]
Hello!
I installed pymlask and conduct `brew install mecab mecab-ipadic`.
But when I tried the Sample, it showed:
`{'text': '彼女のことが嫌いではない！(;´Д`)', 'emotion': None}
`without any other results shown in the bottom part of your sample.
Do you have any ideas how can I fix this problem?
To clarify, I work on a Mac with OS Big Sur, and the python version is 3.7.9.
I would appreciate any help.
Thanks in advance!

**Comment by BiliBraker** [comment]
Same issue on Ubuntu 20.04. LTS with python 3.8.2.

**Comment by yutachaan** [comment]
Same problem happened to me, but I finally resolved  by follow this mecab-ipadic-neologd document https://github.com/neologd/mecab-ipadic-neologd .

If you have installed mecab and mecab-ipadic, try "Preparation of installing" and "How to install/update mecab-ipadic-NEologd" section in the document.

And then, you need to write `emotion_analyzer = MLAsk('-d /usr/local/Caskroom/miniconda/base/lib/mecab/dic/mecab-ipadic-neologd')` in your code. Please rewrite the path part to your own.

My environments is Mac OS Big Sur, and Python 3.9.7.

I hope this will help! 😄

**Comment by EgnaroJQ** [comment]
> Same problem happened to me, but I finally resolved by follow this mecab-ipadic-neologd document https://github.com/neologd/mecab-ipadic-neologd .
> 
> If you have installed mecab and mecab-ipadic, try "Preparation of installing" and "How to install/update mecab-ipadic-NEologd" section in the document.
> 
> And then, you need to write `emotion_analyzer = MLAsk('-d /usr/local/Caskroom/miniconda/base/lib/mecab/dic/mecab-ipadic-neologd')` in your code. Please rewrite the path part to your own.
> 
> My environments is Mac OS Big Sur, and Python 3.9.7.
> 
> I hope this will help! 😄

I really appreciate your advice. It is working very well!
Thank you very much for kind sharing.

**Comment by yin-ori** [comment]
unfortunately it didn't work for me. I retook the steps "preparation of installing" and "how to install mecab-ipadic-NEologd" 
checking the path through 

> echo `mecab-config --dicdir`"/mecab-ipadic-neologd" 
-->
> /opt/homebrew/lib/mecab/dic/mecab-ipadic-neologd

so I went with:
`from mlask import MLAsk`
`emotion_analyzer = MLAsk('-d /opt/homebrew/lib/mecab/dic/mecab-ipadic-neologd')`
`emotion_analyzer.analyze('彼のことは嫌いではない！')` 

but no result coming for me
